// Buttons
export const SEARCH_FILTERS_ICON_TEST = 'SEARCH_FILTERS_ICON_TEST';

// Bottom Tab Buttons
export const FORUM_BOTTOM_TEST = 'FORUM_BOTTOM_TEST';
export const OPTIONS_BOTTOM_TEST = 'OPTIONS_BOTTOM_TEST';
export const YOUR_ACCOUNT_BOTTOM_TEST = 'YOUR_ACCOUNT_BOTTOM_TEST';

// Headers
export const FORUM_HEADER_TEST = 'FORUM_HEADER_TEST';
export const YOUR_ACCOUNT_HEADER_TEST = 'YOUR_ACCOUNT_HEADER_TEST';
export const OPTIONS_HEADER_TEST = 'OPTIONS_HEADER_TEST';

// Elements
export const FLATLIST_FILTERS_TEST = 'FLATLIST_FILTERS';
export const FLATLIST_PUB_ARTICLES_TEST = 'FLATLIST_PUB_ARTICLES_TEST';
